# Generated by Django 3.1.7 on 2021-05-23 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20210523_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
