from django.urls import path
from . import views

urlpatterns = [
    path("", views.apiOverview, name="home"),

    #ALL LISTS
    path("providers/", views.ProviderList, name="providers"),
    path("services/", views.ServiceList, name="services"),
    path("products/", views.ProductList, name="products"),
    path("counties/", views.CountyList, name="counties"),
    path("emergencycontacts/", views.EmergencyContactList, name="emergencycontacts"),
    path("bookings/", views.BookingList, name="boookings"),
    path("staff/", views.StaffList, name="staff"),
    path("roles/", views.RoleList, name="roles"),
    path("categories/", views.CategoryList, name="categories"),
    path("subcategories/", views.SubCategoryList, name="subcategories"),
    path("customers/", views.CustomerList, name="customers"),

    #CREATE URLS
    path("provider-create/", views.ProviderCreate, name="provider-create"),
    path("service-create/", views.ServiceCreate, name="service-create"),
    path("product-create/", views.ProductCreate, name="product-create"),
    path("county-create/", views.CountyCreate, name="county-create"),
    path("emergencycontact-create/", views.EmergencyContactCreate, name="emergencycontact-create"),
    path("category-create/", views.CategoryCreate, name="category-create"),
    path("subcategory-create/", views.SubCategoryCreate, name="subcategory-create"),
    path("customer-create/", views.CustomerCreate, name="customer-create"),
    path("booking-create/", views.BookingCreate, name="booking-create"),
    path("staff-create/", views.StaffCreate, name="staff-create"),
    path("role-create/", views.RoleCreate, name="role-create"),
    #UPDATE URLS
    path("provider-update/<str:pk>/", views.ProviderUpdate, name="provider-update"),
    path("service-update/<str:pk>/", views.ServiceUpdate, name="service-update"),
    path("product-update/<str:pk>/", views.ProductUpdate, name="product-update"),
    path("county-update/<str:pk>/", views.CountyUpdate, name="county-update"),
    path("emergencycontact-update/<str:pk>/", views.EmergencyContactUpdate,
         name="emergencycontact-update"),
    path("category-update/<str:pk>/", views.CategoryUpdate, name="category-update"),
    path("subcategory-update/<str:pk>/", views.SubCategoryUpdate, name="subcategory-update"),
    path("customer-update/<str:pk>/", views.CustomerUpdate, name="customer-update"),
    path("booking-update/<str:pk>/", views.BookingUpdate, name="booking-update"),
    path("staff-update/<str:pk>/", views.StaffUpdate, name="staff-update"),
    path("role-update/<str:pk>/", views.RoleUpdate, name="role-update"),
    #DELETE URLS
    path("provider-delete/<str:pk>/", views.ProviderDelete, name="provider-delete"),
    path("service-delete/<str:pk>/", views.ServiceDelete, name="service-delete"),
    path("product-delete/<str:pk>/", views.ProductDelete, name="product-delete"),
    path("county-delete/<str:pk>/", views.CountyDelete, name="county-delete"),
    path("emergencycontact-delete/<str:pk>/", views.EmergencyContactDelete,
         name="emergencycontact-delete"),
    path("category-delete/<str:pk>/", views.CategoryDelete, name="category-delete"),
    path("subcategory-delete/<str:pk>/", views.SubCategoryDelete, name="subcategory-delete"),
    path("customer-delete/<str:pk>/", views.CustomerDelete, name="customer-delete"),
    path("booking-delete/<str:pk>/", views.BookingDelete, name="booking-delete"),
    path("staff-delete/<str:pk>/", views.StaffDelete, name="staff-delete"),
    path("role-delete/<str:pk>/", views.RoleDelete, name="role-delete"),
    #DETAILS URLS
    path("provider-details/<str:pk>/", views.ProviderDetail, name="provider-details"),
    path("service-details/<str:pk>/",
         views.ServiceDetail, name="service-details"),
    path("product-details/<str:pk>/",
         views.ProductDetail, name="product-details"),
    path("customer-details/<str:pk>/",
         views.CustomerDetail, name="customer-details"),
    path("category-details/<str:pk>/",
         views.CategoryDetail, name="category-details"),
    path("subcategory-details/<str:pk>/",
         views.SubCategoryDetail, name="subcategory-details"),
    path("emergencycontact-details/<str:pk>/",
         views.EmergencyContactDetail, name="emergencycontact-details"),
    path("county-details/<str:pk>/", views.CountyDetail, name="county-details"),
    path("booking-details/<str:pk>/",
         views.BookingDetail, name="booking-details"),
    path("role-details/<str:pk>/",
         views.RoleDetail, name="role-details"),
    path("staff-details/<str:pk>/",
         views.StaffDetail, name="staff-details"),
]
